src/petclinic/urls.py
from django.urls import path
from petclinic import views

# app_name = 'petclinic'

urlpatterns = [
    path('', views.home, name='home'),
    path('find_owner', views.findOwner, name='find_owner'),
    path('add_owner', views.addOwner, name='add_owner'),
    path('owners/<int:pk>', views.ownerDetail, name='owner_info'),
    path('edit_owner/<int:pk>', views.editOwner, name='edit_owner'),
    path('edit_pet/<int:pk>', views.editPet, name='edit_pet'),
    path('add_visit/<int:pk>', views.addVisit, name='add_visit'),
    path('add_pet/<int:pk>', views.addPet, name='add_pet'),
    path('vets_list', views.vetsList, name='vets_list'),
]

src/petclinic_proj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('petclinic/', include('petclinic.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

src/petclinic/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.shortcuts import reverse

class Owners(models.Model):
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=80, blank=True, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('owner_info', args=[str(self.id)])

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        managed = False
        db_table = 'owners'

class Pets(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    type = models.ForeignKey('Types', models.DO_NOTHING)
    owner = models.ForeignKey(Owners, models.DO_NOTHING)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = 'pets'

class Specialties(models.Model):
    name = models.CharField(max_length=80, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = 'specialties'

class Types(models.Model):
    name = models.CharField(max_length=80, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = 'types'

class VetSpecialties(models.Model):
    vet = models.ForeignKey('Vets', models.DO_NOTHING)
    specialty = models.ForeignKey(Specialties, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'vet_specialties'
        unique_together = (('vet', 'specialty'),)


class Vets(models.Model):
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    specialties = models.ManyToManyField(Specialties, through='VetSpecialties')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        managed = False
        db_table = 'vets'

class Visits(models.Model):
    pet = models.ForeignKey(Pets, models.DO_NOTHING)
    visit_date = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'visits'

src/petclinic/forms.py
from django import forms
from django.forms import ValidationError
from petclinic import models
import re

class FindOwnerForm(forms.Form):
    last_name = forms.CharField(
            required=False,
            max_length=30,
            label='',
            error_messages = {'max_length': 'The maximum length for a last name should be less than 30 characters'})

    def clean_last_name(self):
        data = self.cleaned_data['last_name']
        pattern = r'[^\.a-zA-Z]'
        search=re.compile(r'[^a-zA-Z]').search
        if(bool(search(data))):
            raise ValidationError('Last name should contain only characters')

        return data

class NewOwnerForm(forms.ModelForm):
    class Meta:
        model = models.Owners
        fields = '__all__'

class NewPetForm(forms.ModelForm):
    class Meta:
        model = models.Pets
        fields = ('name', 'birth_date', 'type')

class NewVisitForm(forms.ModelForm):
    class Meta:
        model = models.Visits
        fields = ('visit_date', 'description')

src/petclinic/views.py
from django.shortcuts import render, get_object_or_404
from petclinic import forms
from petclinic import models

from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
def home(request):
    return render(request,'petclinic/home.html')

def findOwner(request):
    form = forms.FindOwnerForm()
    if request.method == "POST":
    	form = forms.FindOwnerForm(request.POST)
    	if form.is_valid():
            last_name = form.clean_last_name()
            if len(last_name) == 0:
                owners = models.Owners.objects.all()
            else:
                owners = models.Owners.objects.filter(last_name__exact=last_name)
            if owners.exists():
                # dict = {}
                # for owner in owners:
                #     dict[owner] = models.Pets.objects.filter(owner_id__exact=owner.id)
                return render(request, "petclinic/owners.html", {'owners' : owners}) #{'dict':dict})
            else:
                return render(request, "petclinic/find_owners.html", {'form': form, 'no_owners_found':'No owners with the given last name or there are no owners yet'})

    return render(request, "petclinic/find_owners.html", {"form":form})

def addOwner(request):
    form = forms.NewOwnerForm()

    if request.method == "POST":
    	form = forms.NewOwnerForm(request.POST)
    	if form.is_valid():
            owner = form.save()
            return render(request, "petclinic/owner_info.html", {'owner':owner})

    return render(request, "petclinic/add_owner.html", {'form':form})

def ownerDetail(request, pk):
    try:
        owner = models.Owners.objects.get(id=pk)
        # pets = models.Pets.objects.filter(owner_id=pk)
        # pet_visits = {};
        # for pet in pets:
        #     visits = models.Visits.objects.filter(pet_id=pet.id)
        #     pet_visits[pet] = visits

    except Owners.DoesNotExist:
        raise Http404('Owner does not exist')

    return render(request, 'petclinic/owner_info.html', context={'owner': owner}) # , 'pets_visits': pet_visits

def editOwner(request, pk):
    obj= get_object_or_404(models.Owners, id=pk)
    form = forms.NewOwnerForm(request.POST or None, instance=obj)
    context= {'form': form}

    if request.method == "POST":
        if form.is_valid():
            obj= form.save(commit=False)
            obj.save()
            messages.success(request, "You successfully updated the owner")
            context= {'owner': obj}
            return render(request, 'petclinic/owner_info.html', context)
        else:
            context= {'owner': form, 'error': 'The form was not updated successfully. Please check content'}
    else:
        return render(request,'petclinic/edit_owner.html' , context)

def editPet(request, pk):
    obj= get_object_or_404(models.Pets, id=pk)
    form = forms.NewPetForm(request.POST or None, instance=obj)
    owner = models.Owners.objects.get(id=obj.owner_id)
    context= {'form': form, 'owner': owner}

    if request.method == "POST":
        if form.is_valid():
            obj= form.save(commit=False)
            obj.save()
            messages.success(request, "You successfully updated the pet")
            owner = models.Owners.objects.get(id=obj.owner_id)
            context= {'owner': owner}
            return render(request, 'petclinic/owner_info.html', context)
        else:
            context= {'form': form, 'error': 'The form was not updated successfully. Please check content'}
    else:
        return render(request,'petclinic/edit_pet.html' , context)

def addPet(request, pk):
    form = forms.NewPetForm()
    owner = models.Owners.objects.get(id=pk)
    if request.method == "POST":
    	form = forms.NewPetForm(request.POST)
    	if form.is_valid():
            pet = form.save(commit=False)
            pet.owner_id = pk
            pet.save()
            owner = models.Owners.objects.get(id=pk)
            return render(request, "petclinic/owner_info.html", {'owner':owner})

    return render(request, "petclinic/add_pet.html", {'form':form, 'owner':owner})

def addVisit(request, pk):
    pet = get_object_or_404(models.Pets, id=pk)
    form = forms.NewVisitForm()
    # owner = models.Owners.objects.get(id=obj.owner_id)
    context= {'form': form, 'pet': pet}

    if request.method == "POST":
        form = forms.NewVisitForm(request.POST)
        if form.is_valid():
            visit = form.save(commit=False)
            visit.pet_id = pk
            visit.save()
            messages.success(request, "You successfully saved the pet visit")
            owner = models.Owners.objects.get(id=pet.owner_id)
            context= {'owner': owner}
            return render(request, 'petclinic/owner_info.html', context)
        else:
            context['error'] = 'The visit was not added successfully. Please check content'

    return render(request,'petclinic/add_visit.html' , context)

def vetsList(request):
    vets = models.Vets.objects.all()
    context = {'vets': vets}

    return render(request, 'petclinic/vets.html', context)

src/templates/petclinic/add_owner.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Add New Owner
{% endblock %}

{% block body_block %}
  <h1>New Owner</h1>
  <div class="form">
    <form action="add_owner" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_p }}

      <input type="submit" class="btn btn-primary btn-sm" value="Add Owner"/>

    </table>
  </form>
  </div>

{% endblock %}

src/templates/petclinic/add_pet.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Add New Pet
{% endblock %}

{% block body_block %}
  <h1>New Pet</h1>
  <div class="form">
    <tr>
      <td>Owner: </td><td>{{ owner.first_name }} {{ owner.last_name }}</td>
    </tr>
    <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary btn-sm" value="Add Pet"/>
    </table>
  </form>
  </div>

{% endblock %}

src/templates/petclinic/add_visit.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Add New Owner
{% endblock %}

{% block body_block %}
  <h1>New Visit</h1>
  <div class="content">
  <p>Pet</p>
  <table>
    <tr>
      <th>Name</th>
      <th>Birth Date</th>
      <th>Type</th>
      <th>Owner</th>
    </tr>
    <tr>
      <td>{{ pet.name }}</td>
      <td>{{ pet.birth_date }}</td>
      <td>{{ pet.type.name }}</td>
      <td>{{ pet.owner.first_name }} {{ pet.owner.last_name }}</td>
    </tr>
  </table>
  </div>
  <br><br>
  <div class="form">
    <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary btn-sm" value="Add Visit"/>
    </table>
  </form>
  </div>
  <br><br>
  <div class="content">
    <table>
      <th>Visit Date</th>
      <th>Description</th>
    {% for visit in pet.visits_set.all %}
      <tr>
        <td>{{ visit.visit_date }}</td>
        <td>{{ visit.description }}</td>
      </tr>
    {% endfor %}
    </table>
  </div>
{% endblock %}

src/templates/petclinic/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} Base title {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'home' %}">HOME</a></li>
          <li><a class="nav-item nav-link" href="{% url 'find_owner' %}">FIND OWNERS</a></li>
          <li><a class="nav-item nav-link" href="{% url 'vets_list' %}">VETERINARIANS</a></li>
          <li><a class="nav-item nav-link" href="#">ERRORS</a></li>
          <li><a class="nav-item nav-link" href="{% url 'logout' %}">LOGOUT</a></li>
        </ul>
        <!-- <a class="navbar-brand" href="#">BRAND</a>
        <a class="nav-item nav-link" href="#">Admin</a>
        <a class="nav-item nav-link" href="#">Other</a> -->
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
        <!-- <h1>Welcome Fantastic Library!</h1> -->
      {% endblock %}
    </div>
    <!-- <a href="books/bookpage">Books</a>
    <a href="books/publisherpage">Publishers</a> -->
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
    {% endif %}
  </body>
</html>

src/templates/petclinic/edit_owner.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Owner List
{% endblock %}

{% block body_block %}
<h1>Edit Owner</h1>
<div class="form">
  <form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_p }}

    <input type="submit" class="btn btn-primary btn-sm" value="Update Owner"/>

  </table>
</form>
</div>
{% endblock %}

src/templates/petclinic/edit_pet.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Owner List
{% endblock %}

{% block body_block %}
<h1>Edit Pet</h1>
<div class="form">
  <tr>
    <td>Owner: </td><td>{{ owner.first_name }} {{ owner.last_name }}</td>
  </tr>
  <form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_p }}

    <input type="submit" class="btn btn-primary btn-sm" value="Update Pet"/>

  </table>
</form>
</div>
{% endblock %}

src/templates/petclinic/find_owners.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Find Owner
{% endblock %}

{% block body_block %}
  <h1>Find Owners</h1>
  {% if 'no_owners_found' %}
    <p>{{ no_owners_found }}</p>
  {% endif %}
  <div class="form">
    <form action="find_owner" method="post">
    {% csrf_token %}
    <table>
      <tr><td><label>Last Name:<label></td>
          <td>{{ form.as_p }}</td>
      <tr><td></td>
      <td><input type="submit" class="btn btn-primary btn-sm" value="Find Owner"/><td>
      </tr>
    </table>
  </form>
  </div>
  <div class="content">
    <br><br>
    <a href="{% url 'add_owner' %}" class="btn btn-primary" role="button">Add Owner</a>
  </div>
{% endblock %}

src/templates/petclinic/home.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Home Page
{% endblock %}

{% block body_block %}
  <h1>Welcome to Fantastic Pet Clinic!</h1>
{% endblock %}

src/templates/petclinic/navbar-test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light  float-left">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </nav>
      <nav class="navbar navbar-expand-lg navbar-light bg-light  float-right">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

src/templates/petclinic/owner_info.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Owner Detail
{% endblock %}

{% block body_block %}
  <h1>Owner Information</h1>
  <div class="container">
    <table>
        <tr><th>Name</th><td>{{ owner.first_name }} {{ owner.last_name }}</td></tr>
        <tr><th>Address</th><td>{{ owner.address }}</td></tr>
        <tr><th>City</th><td>{{ owner.city }}</td></tr>
        <tr><th>Telephone</th><td>{{ owner.telephone }}</td></tr>
    </table>
  </div>
  <div class="content">
    <br><br>
    <a href="{% url 'edit_owner' owner.id %}" class="btn btn-primary" role="button">Edit Owner</a>
    <a href="{% url 'add_pet' owner.id %}" class="btn btn-primary" role="button">Add New Pet</a>
  </div
  <br><br>
  <h1>Pets and Visits</h1>
  <div class="container">
    <table>
      {% for pet in owner.pets_set.all %}
      <tr>
        <td> 
          <table>
            <tr>
              <th>Name: </th><td>{{ pet.name }}</td>
            </tr>
            <tr>
              <th>Birth Date:</th><td>{{ pet.birth_date }}</td>
            </tr>
            <tr>
              <th>Type:</th><td> {{ pet.type.name }}</td>
            </tr>
          </table>
        </td>
        <td><table></table></td>
        <td><table></table></td>
        <td>
          <table>
            <tr>
              <th>Visit Date</th>
              <th>Description</th>
            </tr>

            {% for visit in pet.visits_set.all %}
            <tr>
              <td>{{ visit.visit_date }}</td>
              <td>{{ visit.description }}</td>
            </tr>
            {% endfor %}
            <tr>
              <td><a href="{% url 'edit_pet' pet.id %}" class="btn btn-primary" role="button">Edit Pet</a></td>
              <td><a href="{% url 'add_visit' pet.id %}" class="btn btn-primary" role="button">Add Visit</a></td>
            </tr>
          </table>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

src/templates/petclinic/owners.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Owner List
{% endblock %}

{% block body_block %}
  <h1>Owners List </h1>
  {% if 'owners' %}
  <table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>Telephone</th>
    <th>Pets</th>
  </tr>
  <!-- {% for key, value in dict.items %}
  <tr>
    <td>{{ key.first_name }} {{ key.last_name}}</td>
    <td>{{ key.address}}</td>
    <td>{{ key.city}}</td>
    <td>{{ key.telephone}}</td>
    <td>{% for p in value %}
      {{ p }}
    {% endfor %}
    </td>
  </tr>
  {% endfor %} -->
    {% for owner in owners %}
    <tr>
      <td><a href="{{ owner.get_absolute_url }}">{{ owner.first_name }} {{ owner.last_name}}</a></td>
      <td>{{ owner.address}}</td>
      <td>{{ owner.city}}</td>
      <td>{{ owner.telephone}}</td>
      <td>
        {% for pet in owner.pets_set.all %}
          {{ pet }}
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
{% endblock %}

src/templates/petclinic/vets.html
<!DOCTYPE html>
{% extends "./base.html" %}

{% block title %}
  Owner List
{% endblock %}

{% block body_block %}
  <h1>VETERINARIANS </h1>
  {% if 'vets' %}
  <table>
  <tr>
    <th>Name</th>
    <th>Specialties</th>
  </tr>
    {% for vet in vets %}
    <tr>
      <td>{{ vet }}</td>
      <td>
        {% for specialty in vet.specialties.all %}
          {{ specialty }}
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
{% endblock %}